quarkus:
  http:
    cors: true
    port: 8081

kafka:
  bootstrap:
    servers: localhost:29092

mp:
  messaging:
    incoming:
      test-in:
        topic: test
        connector: smallrye-kafka
        value:
          deserializer: com.practice.musicsalesgood.kafka.serializer.TestMessageSerializer
    outgoing:
      test-out:
        connector: smallrye-kafka
        topic: test
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer