quarkus:
  http:
    cors: true
    port: 8081
  kafka:
    devservices:
      topic-partitions:
        music_sales_stream_local_good: 1
        music_sales_stream_local_bad: 1

kafka:
  bootstrap:
    servers: localhost:29092

mp:
  messaging:
    incoming:
      event-in-good:
        topic: music_sales_stream_local_good
        connector: smallrye-kafka
        value:
          deserializer: com.practice.kafka.serializer.MusicShopEventSerializer
    outgoing:
      event-out-good:
        connector: smallrye-kafka
        topic: music_sales_stream_local_good
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      event-out-bad:
        connector: smallrye-kafka
        topic: music_sales_stream_local_bad
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer